package com.aether.renderer

enum class PlannerScenarioKind {
    STABLE,
    UNCERTAIN,
    RISKY,
    LOCKED,
    LOW_CONFIDENCE
}

data class PlannerScenario(
    val id: String,
    val kind: PlannerScenarioKind,
    val packageName: String,
    val contextLabel: String,
    val screenType: ScreenType,
    val observerActive: Boolean,
    val nodeCount: Int,
    val clickableCount: Int,
    val textNodeCount: Int,
    val depth: Int,
    val confidence: Float,
    val risk: Float,
    val uncertainty: Float,
    val volatility: Float,
    val trustScore: Float,
    val stateStability: Float,
    val privacyMode: PrivacyMode,
    val securityMode: SecurityLockMode,
    val budgetMode: RuntimeBudgetMode,
    val expectedBand: IntentReadinessBand,
    val expectedIntent: StrategicIntentType,
    val reason: String
) {
    fun toPhysicsState(): PhysicsExperienceState {
        val density = if (nodeCount <= 0) 0.0f else ((clickableCount * 0.55f + textNodeCount * 0.20f) / nodeCount.toFloat()).coerceIn(0.0f, 1.0f)
        return PhysicsExperienceState(
            packageName = packageName,
            contextLabel = contextLabel,
            screenType = screenType,
            observerActive = observerActive,
            nodeCount = nodeCount,
            clickableCount = clickableCount,
            textNodeCount = textNodeCount,
            depth = depth,
            confidence = confidence.coerceIn(0.0f, 1.0f),
            risk = risk.coerceIn(0.0f, 1.0f),
            trustScore = trustScore.coerceIn(0.0f, 1.0f),
            uncertainty = uncertainty.coerceIn(0.0f, 1.0f),
            volatility = volatility.coerceIn(0.0f, 1.0f),
            privacyMode = privacyMode,
            securityMode = securityMode,
            budgetMode = budgetMode,
            interactionDensity = density,
            stateStability = stateStability.coerceIn(0.0f, 1.0f),
            telemetryOnly = true,
            autoControlEnabled = false,
            reason = "scenario_${kind.name.lowercase(java.util.Locale.US)}"
        )
    }

    companion object {
        fun defaultMatrix(): List<PlannerScenario> = listOf(
            PlannerScenario(
                id = "stable_ready",
                kind = PlannerScenarioKind.STABLE,
                packageName = "com.example.reader",
                contextLabel = "CTX_STABLE_READER",
                screenType = ScreenType.SCREEN_LIST,
                observerActive = true,
                nodeCount = 48,
                clickableCount = 8,
                textNodeCount = 24,
                depth = 7,
                confidence = 0.86f,
                risk = 0.08f,
                uncertainty = 0.12f,
                volatility = 0.06f,
                trustScore = 0.76f,
                stateStability = 0.82f,
                privacyMode = PrivacyMode.STANDARD,
                securityMode = SecurityLockMode.OPEN_OBSERVE,
                budgetMode = RuntimeBudgetMode.NORMAL,
                expectedBand = IntentReadinessBand.READY,
                expectedIntent = StrategicIntentType.MAINTAIN_READY,
                reason = "baseline_ready_low_risk_high_confidence"
            ),
            PlannerScenario(
                id = "uncertain_context",
                kind = PlannerScenarioKind.UNCERTAIN,
                packageName = "com.example.dynamic",
                contextLabel = "CTX_UNCERTAIN_DYNAMIC",
                screenType = ScreenType.SCREEN_UNKNOWN,
                observerActive = true,
                nodeCount = 22,
                clickableCount = 4,
                textNodeCount = 5,
                depth = 10,
                confidence = 0.52f,
                risk = 0.18f,
                uncertainty = 0.70f,
                volatility = 0.18f,
                trustScore = 0.40f,
                stateStability = 0.50f,
                privacyMode = PrivacyMode.STANDARD,
                securityMode = SecurityLockMode.OPEN_OBSERVE,
                budgetMode = RuntimeBudgetMode.WATCH,
                expectedBand = IntentReadinessBand.CAUTION,
                expectedIntent = StrategicIntentType.SEEK_CLARITY,
                reason = "uncertainty_should_shift_to_clarity"
            ),
            PlannerScenario(
                id = "risky_confirm",
                kind = PlannerScenarioKind.RISKY,
                packageName = "com.example.checkout",
                contextLabel = "CTX_RISK_CONFIRM",
                screenType = ScreenType.SCREEN_CONFIRM,
                observerActive = true,
                nodeCount = 36,
                clickableCount = 3,
                textNodeCount = 12,
                depth = 8,
                confidence = 0.68f,
                risk = 0.48f,
                uncertainty = 0.30f,
                volatility = 0.22f,
                trustScore = 0.50f,
                stateStability = 0.60f,
                privacyMode = PrivacyMode.SENSITIVE,
                securityMode = SecurityLockMode.GUARDED,
                budgetMode = RuntimeBudgetMode.THROTTLE,
                expectedBand = IntentReadinessBand.SAFETY,
                expectedIntent = StrategicIntentType.REDUCE_RISK,
                reason = "risk_should_shift_to_safety"
            ),
            PlannerScenario(
                id = "locked_private",
                kind = PlannerScenarioKind.LOCKED,
                packageName = "com.example.securewallet",
                contextLabel = "CTX_PRIVATE_LOCKED",
                screenType = ScreenType.SCREEN_FORM,
                observerActive = true,
                nodeCount = 18,
                clickableCount = 2,
                textNodeCount = 6,
                depth = 6,
                confidence = 0.62f,
                risk = 0.52f,
                uncertainty = 0.36f,
                volatility = 0.18f,
                trustScore = 0.30f,
                stateStability = 0.56f,
                privacyMode = PrivacyMode.LOCKED,
                securityMode = SecurityLockMode.HARD_LOCK,
                budgetMode = RuntimeBudgetMode.CRITICAL,
                expectedBand = IntentReadinessBand.SAFETY,
                expectedIntent = StrategicIntentType.REVIEW_PRIVACY,
                reason = "hard_lock_should_force_privacy_review"
            ),
            PlannerScenario(
                id = "low_confidence",
                kind = PlannerScenarioKind.LOW_CONFIDENCE,
                packageName = "com.example.loading",
                contextLabel = "CTX_LOW_CONFIDENCE",
                screenType = ScreenType.SCREEN_LOADING,
                observerActive = true,
                nodeCount = 8,
                clickableCount = 1,
                textNodeCount = 1,
                depth = 3,
                confidence = 0.32f,
                risk = 0.16f,
                uncertainty = 0.72f,
                volatility = 0.12f,
                trustScore = 0.24f,
                stateStability = 0.46f,
                privacyMode = PrivacyMode.STANDARD,
                securityMode = SecurityLockMode.OPEN_OBSERVE,
                budgetMode = RuntimeBudgetMode.WATCH,
                expectedBand = IntentReadinessBand.CAUTION,
                expectedIntent = StrategicIntentType.SEEK_CLARITY,
                reason = "low_confidence_should_not_ready"
            )
        )
    }
}
